# https://github.com/samuelmeuli/action-electron-builder
name: Run audit checks

on:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Upgrade to Yarn 3.0
        run: |
          yarn set version 3.0
      
      - name: Remove any cached files
        run: |
          rm -Rf ./node_modules && rm -Rf ./.yarn/cache && rm -Rf ./.yarn/unplugged

      - name: Refresh
        run: |
          sudo apt-get update

      - name: Setup dependencies
        run: |
          sudo apt-get install -y libusb-1.0-0-dev libudev-dev

      - name: Audit dependencies
        # Now using the audit tool from IBM which provides more advanced configurability.
        # The `allowlist` property in .audit-ci.jsonc supports allowlisting advisories.
        # E.g is the false positive submission on lodash:
        # https://github.com/lodash/lodash/issues/5261
        # Installing dependencies is not required for auditing.
        run: |
          yarn dlx audit-ci@^6 --config .audit-ci.jsonc

